# Generated by Django 5.2.6 on 2025-11-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
